name: CI
on:
  push:
    branches:
    - master
    tags:
    - "v*"
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - uses: coursier/cache-action@v5

    - uses: olafurpg/setup-scala@v10
      with:
        java-version: adopt@1.11

    - name: Run tests
      run: sbt scripted versionPolicyCheck

  publish:
    needs: test
    if: github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: coursier/cache-action@v5

      - uses: olafurpg/setup-scala@v10

      - name: Release
        run: sbt versionCheck ci-release
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
